### ISSUE TITLE
Java 9 support

### ISSUE THREAD

**Issue by benkuly** [authzforce/core#12]
Is support for Java 9 planned? Actually I'm getting `JAXBException` with Java 9.

**Comment by cdanger** [comment]
Not yet, can you give the full stracktrace?

**Comment by benkuly** [comment]
I'm getting a `java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException`.
I've found a potential solution [here](https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j).

**Comment by cdanger** [comment]
alright, good to know for the future.
