### ISSUE TITLE
Failed Permitted Access XACML

### ISSUE THREAD

**Issue by ihsanhaikalz** [authzforce/core#15]
# Software version (AuthzForce Core)
10.2.0
# Platform JRE
1.8.0_162
# Platform OS
Windows 7
# Error stack trace or logs (if any)
*If in doubt include the whole thing; often exceptions get wrapped in other exceptions and the exception right near the bottom explains the actual error, not the first few lines at the top.*

# Your code and/or AuthzForce-specific configuration file(s)
I am currently trying to implement XACML for an application and just started playing around it using AuthZForce library. I have an example policy such as:

    <?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <Policy xmlns="urn:oasis:names:tc:xacml:3.0:core:schema:wd-17" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" PolicyId="urn:oasis:names:tc:xacml:2.0:conformance-test:IIA1:policy" RuleCombiningAlgId="urn:oasis:names:tc:xacml:3.0:rule-combining-algorithm:deny-overrides" Version="1.0">
        <Description>
            Policy for Conformance Test IIA001.
        </Description>
        <Target/>
        <Rule Effect="Permit" RuleId="urn:oasis:names:tc:xacml:2.0:conformance-test:IIA1:rule">
            <Description>
                Julius Hibbert can read or write Bart Simpson's medical record.
            </Description>
            <Target>
                <AnyOf>
                    <AllOf>
                        <Match MatchId="urn:oasis:names:tc:xacml:1.0:function:string-equal">
                            <AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">Julius Hibbert</AttributeValue>
                            <AttributeDesignator AttributeId="urn:oasis:names:tc:xacml:1.0:subject:subject-id" Category="urn:oasis:names:tc:xacml:1.0:subject-category:access-subject" DataType="http://www.w3.org/2001/XMLSchema#string" MustBePresent="false"/>
                        </Match>
                    </AllOf>
                </AnyOf>
                <AnyOf>
                    <AllOf>
                        <Match MatchId="urn:oasis:names:tc:xacml:1.0:function:anyURI-equal">
                            <AttributeValue DataType="http://www.w3.org/2001/XMLSchema#anyURI">http://medico.com/record/patient/BartSimpson</AttributeValue>
                            <AttributeDesignator AttributeId="urn:oasis:names:tc:xacml:1.0:resource:resource-id" Category="urn:oasis:names:tc:xacml:3.0:attribute-category:resource" DataType="http://www.w3.org/2001/XMLSchema#anyURI" MustBePresent="false"/>
                        </Match>
                    </AllOf>
                </AnyOf>
                <AnyOf>
                    <AllOf>
                        <Match MatchId="urn:oasis:names:tc:xacml:1.0:function:string-equal">
                            <AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">read</AttributeValue>
                            <AttributeDesignator AttributeId="urn:oasis:names:tc:xacml:1.0:action:action-id" Category="urn:oasis:names:tc:xacml:3.0:attribute-category:action" DataType="http://www.w3.org/2001/XMLSchema#string" MustBePresent="false"/>
                        </Match>
                    </AllOf>
                    <AllOf>
                        <Match MatchId="urn:oasis:names:tc:xacml:1.0:function:string-equal">
                            <AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">write</AttributeValue>
                            <AttributeDesignator AttributeId="urn:oasis:names:tc:xacml:1.0:action:action-id" Category="urn:oasis:names:tc:xacml:3.0:attribute-category:action" DataType="http://www.w3.org/2001/XMLSchema#string" MustBePresent="false"/>
                        </Match>
                    </AllOf>
                </AnyOf>
            </Target>
        </Rule>
    </Policy>

So I tried to creat XACML request based on this policy, hoping that it will be permitted by PDP with the code as follow:

    System.setProperty("javax.xml.accessExternalSchema", "http");
    
    		File a = new File("pdp.xml");
    
    
    		final PdpEngineConfiguration pdpEngineConf = PdpEngineConfiguration.getInstance(a.toURI().toString()); 
    		final BasePdpEngine pdp = new BasePdpEngine(pdpEngineConf);
    		final DecisionRequestBuilder<?> requestBuilder = pdp.newRequestBuilder(-1, -1);
    		String issuer="Julius Hibbert";
    
    		final AttributeFqn subjectIdAttributeId = AttributeFqns.newInstance(XACML_1_0_ACCESS_SUBJECT.value(), Optional.ofNullable(issuer), XacmlAttributeId.XACML_1_0_SUBJECT_ID.value());
    		final AttributeBag<?> subjectIdAttributeValues = Bags.singletonAttributeBag(StandardDatatypes.STRING, new StringValue("Julius Hibbert"));
    		requestBuilder.putNamedAttributeIfAbsent(subjectIdAttributeId, subjectIdAttributeValues);
    
    		final AttributeFqn resourceIdAttributeId = AttributeFqns.newInstance(XACML_3_0_RESOURCE.value(), Optional.ofNullable(issuer), XacmlAttributeId.XACML_1_0_RESOURCE_ID.value());
    		final AttributeBag<?> resourceIdAttributeValues = Bags.singletonAttributeBag(StandardDatatypes.STRING, new StringValue("http://medico.com/record/patient/BartSimpson"));
    		requestBuilder.putNamedAttributeIfAbsent(resourceIdAttributeId, resourceIdAttributeValues);
    
    		// Add action ID attribute (action category), no issuer, string value "GET"
    		final AttributeFqn actionIdAttributeId = AttributeFqns.newInstance(XACML_3_0_ACTION.value(), Optional.ofNullable(issuer), XacmlAttributeId.XACML_1_0_ACTION_ID.value());
    		final AttributeBag<?> actionIdAttributeValues = Bags.singletonAttributeBag(StandardDatatypes.STRING, new StringValue("write"));
    		requestBuilder.putNamedAttributeIfAbsent(actionIdAttributeId, actionIdAttributeValues);
    
    		// No more attribute, let's finalize the request creation
    		final DecisionRequest request = requestBuilder.build(false);
    		// Evaluate the request
    		final DecisionResult result = pdp.evaluate(request);
    		if(result.getDecision() == DecisionType.PERMIT) {
    			// This is a Permit :-)
    			System.out.println("ok");
    		} else {
    			// Not a Permit :-( (maybe Deny, NotApplicable or Indeterminate)
    			System.out.println("not ok");
    		}

But when I run the code it gave the result of NotApplicable but I am not sure why. Is there any error in my code?

**Comment by cdanger** [comment]
The datatype of the `resource-id` attribute is wrong in your code. You set it to `string` whereas in the policy the Match requires `anyURI`. So just change this line of code:

```java
final AttributeBag<?> resourceIdAttributeValues = Bags.singletonAttributeBag(StandardDatatypes.STRING, new StringValue("http://medico.com/record/patient/BartSimpson"));
```
to
```java
final AttributeBag<?> resourceIdAttributeValues = Bags.singletonAttributeBag(StandardDatatypes.ANYURI, new AnyUriValue("http://medico.com/record/patient/BartSimpson"));
```
Also, any particular reason why you are setting the Issuer of the attributes to `Julius Hibbert`? Else set it to null and don't worry about it.

```java
String issuer = null;
```

**Comment by cdanger** [comment]
answered on:
https://stackoverflow.com/questions/50326319/failed-permitted-access-xacml/50339793?noredirect=1#comment87716720_50339793
