### ISSUE TITLE
Confused due to redundant repositories including redundant documentation

### ISSUE THREAD

**Issue by OneWorld123** [authzforce/core#16]
Hi,

first of all, thank you for all the hard work you and Ferrari have contributed to that project!

Now, here is my question: Could you please make a statement regarding your two repositories? Which one is active/deprecated? Where is the documentation complete? Maybe you could mark one of them as deprecated in its README.md?

- https://github.com/authzforce/core
- https://gitlab.ow2.org/authzforce/core

**Comment by cdanger** [comment]
I understand the confusion, but for the moment, this github is more up-to-date for both code and documentation. (We are considering full migration to ow2.org one day but not ready so far, we are using github as reference and synchronizing the code with gitlab from time to time.)
