### ISSUE TITLE
LDAP profile

### ISSUE THREAD

**Issue by OneWorld123** [authzforce/core#18]
Romain Ferrari said on the OW2con'16 _"We support some of the well known OASIS profiles, such as the LDAP profile which [h]andle[s] the Role Based Access Control within XACML"_ at https://youtu.be/c6om2J9Wno0?t=5m2s 5:02

That made me curious about the LDAP xacml profile. LDAP is planned in our design for authorization and as a data storage for subject attributes.

What profile is he referring to? Can I make use out of it? All I can find on https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=xacml is _"LDAP profile for distribution of XACML policies [...] [is a work item which is] not currently under active development or discussion, but [has] not officially been withdrawn."_

**Comment by cdanger** [comment]
Unfortunately, he meant the **RBAC** profile. That's the one: http://docs.oasis-open.org/xacml/3.0/rbac/v1.0/xacml-3.0-rbac-v1.0.html . As for the LDAP profile, it is a proposal for using a LDAP directory as PRP (policy repository). There has not been any follow-up on it by the XACML TC, so it is far from being standard. So in short, RBAC profile is supported by AuthzForce, LDAP profile is not.

Yet, you mention planning to use LDAP directory for storage of subject attributes. In order for the PDP to get attributes from LDAP, you can implement an Attribute Provider extension to AuthzForce.
