### ISSUE TITLE
What datatype do you use for http://www.w3.org/2001/XMLSchema#integer?

### ISSUE THREAD

**Issue by OneWorld123** [authzforce/core#19]
The docs about http://www.w3.org/2001/XMLSchema#integer says:

> The type xsd:integer represents an **arbitrarily** large integer, from which twelve other built-in integer types are derived (directly or indirectly). An xsd:integer is a sequence of digits, optionally preceded by a + or - sign. Leading zeros are permitted, but decimal points are not.
> 
> http://www.datypic.com/sc/xsd/t-xsd_integer.html

However, I am sure your PDP cannot handle **arbitrarily** large integers since JAVA has no endless large integer datatype. So, whats your maximum integer number?

I'm asking, because I have to decide which datatype to use for the ID of a resource (the ID is stored in the DB as a numeric value).

**Comment by cdanger** [comment]
The Java type depends on the `maxIntegerValue` parameter in PDP configuration ( [schema](https://github.com/authzforce/core/blob/develop/pdp-engine/src/main/resources/pdp.xsd) ):
- If it is small enough to fit in a Java Integer, then the PDP uses Integer.
- Else if it is small enough to fit in a Java Long, then use Long.
- Else use BigInteger.
So the biggest value ever that the PDP supports is the max value allowed by Java BigInteger on your JRE.

**Comment by OneWorld123** [comment]
You answered my question! Thanks!
