### ISSUE TITLE
How to query policies

### ISSUE THREAD

**Issue by OneWorld123** [authzforce/core#20]
I wonder if your PDP can offer something similar that axiomatics calls ARQ (Axiomatics Reverse Query). Here is an example from their [docs](https://www.axiomatics.com/product/axiomatics-data-access-filter-adaf/axiomatics-reverse-query/): 

> A standard XACML request can be answered with a Permit or Deny. “Can user Bob read document number 42 from the database management system?” Permit or deny.
> 
> An ARQ response, by contrast, is a logical expression. The PEP sends an open request to the PDP. “Which actions can Bob perform on documents in this repository?” The response may include criteria such as “Permit read access for documents belonging to Bob’s department, Write access for documents authored by Bob or users for whom he is the manager, namely Anne, Joe or Charlie or for which Bob is the assigned reviewer or editor”.

**Comment by OneWorld123** [comment]
Hi Cyril,

here's my usecase:

Nurses are only allowed to view exams 30 days in the past, doctors are allowed to view them 90 days in the past. Therefore I need to adjust the query like

`SELECT * FROM exams WHERE editDate > now - numberAllowedOfDays`

So, my aim is to ask the PDP for the amount of days the current subject is allowed to view into the past. The simple response "deny" or "permit" is not sufficient enough for that use case.

**Comment by OneWorld123** [comment]
Hi Cyrill,

I'd like to give you feedback on my evaluation that still hasn't ended yet. But so far, it becomes apparent that we decide against using this PDP and probably against using XACML at all. The main reason is this point. 

For my understanding XACML has been designed for single records. Here it plays out all it strengths:

- Straight forward interface (Deny, Permit)
- Superior flexibility

But the designers of XACML failed to provide a way of securing queries. Howerver, queries are the first step to work with single records.
- Multiple Decision Profile of XACML 3.0 is not helpful, because I can't ask the PDP for a million of records. Maybe, the one million and first record is the first record the user is allowed to view?
- Obligations never can provide the semantics like “Permit read access for documents belonging to Bob’s department, Write access for documents authored by Bob or users for whom he is the manager, namely Anne, Joe or Charlie or for which Bob is the assigned reviewer or editor”
- If one tries to implement securing queries using XACML, then all the sudden the nicely encapsulated logic of the PDP needs to move into the business logic. It's no longer the PDP saying "Give me all attributes and I decide". Instead, we start to make assumptions like "The query includes a condition for a certain attribute in the where clause, how to fill it?" 

How do your projects cope with that limitation?

**Comment by veotax** [comment]
@OneWorld123 XACML is an old artifact. You can consider: https://github.com/casbin/jcasbin

**Comment by cdanger** [comment]
You might want to ask about this issue on the [XACML users mailing list](https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=xacml#feedback) to reach a larger XACML community.

As far as the AuthzForce team is concerned, in most cases like this we deal with, the number of records is small enough for the Multiple Decision Profile to give satisfaction. In the few minor cases where it is not, we implemented partial evaluation to some extent but without the policy-to-SQL conversion part that ARQ does; and we don't provide that as open source in AuthzForce yet.
