### ISSUE TITLE
How to get policies from classpath from different jar files.

### ISSUE THREAD

**Issue by miladamery** [authzforce/core#28]
authzforce-ce-core-pdp-engine
13.2.0
1.8.0_131

Windows 10

Hi, suppose that i have multiple spring projects that have their own authz rules. each of these projects has a authz_policies directory under their resource folder which has *.xml files that stored policies.
all of this projects are going to depend on jar file that i created and implemented authzforce requirements to work. lets call this authzforceAuthz. how can i say in pdp.xml of authzforceAuthz project
too look in classpath for all authz_policies folder and pick every *.xml file under them as policies.

i want somehow same kind of config that dozerMapper use in spring. when i want to config dozer mapper i say :
```
import org.springframework.core.io.Resouce;

@Configuration
public class DozerConfiguration {

@Value("classpath*:dozerMapping/**/*.xml")
private Resource[] resources;

.
. creating dozer mapper bean with given resources
.
}
```
after this dozzer uses all *.xml files under dozerMapping folder, this folder is in project dependency jar files and also exist in project resource folder. all of them are given to dozzer.

how can i do the same thing for *_policy.xml files?

what i truly need is i want to secure my controller methods (spring mvc) with spring security @preAuthorize. i want to create a policy file for each controller and put authorization logic in that file. these policy files are independent. they don't need each other. each project has defined its own policies and put them under authz_policies folder in their respective jar file. i want to load all those files into authzforce engine.

**Comment by cdanger** [comment]
Yes, you can use this kind of '*' pattern for policy locations in pdp.xml. The PDP configuration [XML schema](https://github.com/authzforce/core/blob/master/pdp-engine/src/main/resources/pdp.xsd) describes all the possibilities of PDP configuration, in particular the StaticRefPolicyProvider's policyLocation attribute.  For example (if you don't understand XML schema), you can use it like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<pdp xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://authzforce.github.io/core/xmlns/pdp/6.0" version="6.0.0">
   <refPolicyProvider id="refPolicyprovider" xsi:type="StaticRefPolicyProvider">
	<policyLocation>${PARENT_DIR}/policies/**.xml</policyLocation>
   </refPolicyProvider>
   <rootPolicyProvider id="rootPolicyProvider" xsi:type="StaticRefBasedRootPolicyProvider">
       <policyRef>root</policyRef>
   </rootPolicyProvider>
</pdp>
```

**Comment by miladamery** [comment]
i use java config
```
@Bean
public BasePdpEngine authzForceEngine() {
   PdpEngineConfiguration config = PdpEngineConfiguration.getInstance("classpath:pdp.xml","classpath:catalog.xml","classpath:pdp-ext.xsd");
   BasePdpEngine xacmlEngine = new BasePdpEngine(config);
   return xacmlEngine;
}

**Comment by cdanger** [comment]
Yes, the issue is "classpath:pdp.xml". You must use a filesystem location for the pdp.xml like in my example. This is better anyway to load the pdp.xml as normal file and not from classpath. This way, you can change the PDP configuration without creating a new JAR.
