### ISSUE TITLE
Integration for spring boot and spring security

### ISSUE THREAD

**Issue by miladamery** [authzforce/core#30]
I want to use Authzforce in spring boot projects.
for now i did something like this:
```
@Bean
    public BasePdpEngine xacmlEngine() throws Exception {
        PdpEngineConfiguration pdpEngineConfig = PdpEngineConfiguration.getInstance("classpath:pdp.xml",
                "classpath:catalog.xml", "classpath:pdp-ext.xsd");
        BasePdpEngine pdpEngine = new BasePdpEngine(pdpEngineConfig);
        return pdpEngine;
    }
```
.xml files exist under resource folder and it works.
i want to know if you can provide a solid spring integration. so we can use java config, using spring resources, configuring pdp as a bean instead of xml , etc.

**Comment by cdanger** [comment]
The cxf-spring-boot-server module of [AuthzForce RESTful PDP](https://github.com/authzforce/restful-pdp) project uses AuthzForce in a Spring Boot app to create a RESTful PDP service as executable JAR. You can check the code there.
