### ISSUE TITLE
is there a PHP client that can be integrated with Symfony?

### ISSUE THREAD

**Issue by videni** [authzforce/core#36]
Hi, I am looking for a PDP companion  for PHP that can be integrated with Symfony? is there a solution ? if not, can you give me some guides on what need to do to write a PHP client like this one ?

**Comment by cdanger** [comment]
We don't provide one out-of-the-box but the implementation is quite simple if you use the REST API, either from the minimal AuthzForce [restful-pdp project](https://github.com/authzforce/restful-pdp) or the more feature-rich/heavyweight [server project](https://github.com/authzforce/server). Both comply with the [REST Profile of XACML](http://docs.oasis-open.org/xacml/xacml-rest/v1.0/xacml-rest-v1.0.html) and [JSON Profile of XACML](http://docs.oasis-open.org/xacml/xacml-json-http/v1.1/xacml-json-http-v1.1.html) for the payload (XACML Request/Response). 

So you can call the PDP's REST API with your favorite HTTP/REST framework in PHP, and for generating the XACML Request, I recommend you use a [template engine](http://acmeextension.com/best-templating-engine/) and make the Request template part of the client configuration. Just for example in other programming languages:
* [XACML/JSON Request template using Jinja template engine for Python](https://github.com/authzforce/python-xacml-sdk/issues/1);
* [XACML/JSON Request using Freemarker template engine for Java](https://github.com/DRIVER-EU/kafka-combined-acl-xacml-authorizer/blob/develop/src/test/resources/request.xacml.json.ftl).
