### ISSUE TITLE
Create custom attribute provider as in wiki example fails

### ISSUE THREAD

**Issue by Nickath** [authzforce/core#46]
# Software version (AuthzForce Core)
   13.3.1

# Platform JRE
   1.8

# Platform OS
   Ubuntu

# Error stack trace or logs (if any)

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<error xmlns:ns2="http://authzforce.github.io/core/xmlns/pdp/6.0" xmlns:ns3="urn:oasis:names:tc:xacml:3.0:core:schema:wd-17">
    <message>Invalid parameters: cvc-elt.4.2: Cannot resolve 'test:TestAttributeProvider' to a type definition for element 'attributeProvider'.</message>
</error>
```

Hello, I am trying to follow from the  [wiki](https://github.com/authzforce/core/wiki/Attribute-Providers#how-the-pdp-uses-attribute-providers) the attribute providers section in order to **add a custom PIP in my authzforce server.** 

What I did:

1) Downloaded from [here](https://repo1.maven.org/maven2/org/ow2/authzforce/authzforce-ce-core-pdp-testutils/13.3.1/) the authzforce-ce-core-pdp-testutils.13.3.1.jar since my`authzforce-ce-core-pdp-engine` version is that and placed it in the classpath `/opt/authzforce-ce-server/webapp/WEB-INF/lib`.

2) Imported the attribute provider XML schema in the XML schema file 
   `/opt/authzforce-ce-server/conf/authzforce-ext.xsd` code

```xml
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://authzforce.github.io/rest-api-model/xmlns/authzforce/ext" xmlns:tns="http://authzforce.github.io/rest-api-model/xmlns/authzforce/ext" elementFormDefault="qualified" attributeFormDefault="unqualified" version="4.0">
	<xs:annotation>
		<xs:documentation xml:lang="en">
			Schemas of enabled AuthZForce extensions, such as attribute providers.
		</xs:documentation>
	</xs:annotation>
	<!-- Extension for file-based PAP DAO root/ref policy providers -->
	<xs:import namespace="http://authzforce.github.io/core/xmlns/test/3" />
	<xs:import namespace="http://authzforce.github.io/pap-dao-flat-file/xmlns/pdp-ext/3.6" />
</xs:schema>
```

3) Added a uri element to XML catalog file `/opt/authzforce-ce-server/conf/catalog.xml` 

```xml
 <?xml version="1.0" encoding="UTF-8"?>
<catalog xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog">
	<systemSuffix systemIdSuffix="xml.xsd" uri="classpath:xml.xsd"/>
	<uri name="http://www.w3.org/2005/Atom" uri="classpath:atom.xsd"/>
	<uri name="urn:oasis:names:tc:xacml:3.0:core:schema:wd-17" uri="classpath:xacml-core-v3-schema-wd-17.xsd"/>
	<uri name="http://authzforce.github.io/xmlns/pdp/ext/3" uri="classpath:pdp-ext-base.xsd"/>
	<system systemId="authzforce-ext.xsd" uri="classpath:authzforce-ext.xsd"/>
	
	<!-- PDP Extensions -->
	<uri name="http://authzforce.github.io/core/xmlns/test/3" uri="classpath:org.ow2.authzforce.core.pdp.testutil.ext.xsd"/>
	<uri name="http://authzforce.github.io/pap-dao-flat-file/xmlns/pdp-ext/3.6" uri="classpath:org.ow2.authzforce.pap.dao.flatfile.pdp-ext.xsd"/>
</catalog>

```

4) Restarted tomcat server

Following the example, I thought that I should now be able to get my new attribute provider through `GET /domains/{domainId}/pap/attribute/providers` but that does not happen. 

*Response*

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:attributeProviders xmlns="http://authzforce.github.io/pap-dao-flat-file/xmlns/properties/3.6" xmlns:ns2="http://authzforce.github.io/rest-api-model/xmlns/authz/5" xmlns:ns3="urn:oasis:names:tc:xacml:3.0:core:schema:wd-17" xmlns:ns4="http://www.w3.org/2005/Atom" xmlns:ns5="http://authzforce.github.io/core/xmlns/pdp/6.0"/>
```

Tried also to send a request instantiating a specific `TestAttributeProvider` on my created domain as In your example 

`PUT /domains/iMnxv7sDEeWFwqVFFMDLTQ/pap/attribute.providers
HTTP/1.1
Accept: application/xml; charset=UTF-8
Content-Type: application/xml; charset=UTF-8

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<attributeProviders
 xmlns="http://authzforce.github.io/rest-api-model/xmlns/authz/5"
 xmlns:xacml="urn:oasis:names:tc:xacml:3.0:core:schema:wd-17">
 <attributeProvider
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:test="http://authzforce.github.io/core/xmlns/test/3"
  xsi:type="test:TestAttributeProvider" id="test">
  <xacml:Attributes
   Category="urn:oasis:names:tc:xacml:1.0:subject-category:access-subject">
   <xacml:Attribute AttributeId="urn:oasis:names:tc:xacml:1.0:example:attribute:role"
    IncludeInResult="false">
    <xacml:AttributeValue
     DataType="http://www.w3.org/2001/XMLSchema#string">Physician</xacml:AttributeValue>
   </xacml:Attribute>
  </xacml:Attributes>
 </attributeProvider>
</attributeProviders>
```

but I am getting as response 

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<error xmlns:ns2="http://authzforce.github.io/core/xmlns/pdp/6.0" xmlns:ns3="urn:oasis:names:tc:xacml:3.0:core:schema:wd-17">
    <message>Invalid parameters: cvc-elt.4.2: Cannot resolve 'test:TestAttributeProvider' to a type definition for element 'attributeProvider'.</message>
</error>
```

Why that happens? Doesn't the jar indicating in the example for maven repo have the TestAttributeProvider class?

**Comment by cdanger** [comment]
Hello, you copy-pasted the XML schema twice (also for the XML catalog) by mistake I assume. Could you give the actual catalog.xml ?

**Comment by Nickath** [comment]
Really sorry about that, I edited my question above, (problem remains the same).

**Comment by cdanger** [comment]
In the request to `.../pap/attribute.providers`, it should be `test:TestAttributeProviderDescriptor` instead of `test:TestAttributeProvider`. Please fix and try again.

**Comment by Nickath** [comment]
It worked! Thank you very much, I copied the code from the example [here](https://authzforce-ce-fiware.readthedocs.io/en/latest/UserAndProgrammersGuide.html#programmer-guide) that's why it was `TestAttributeProvider`. Now in case I would like the newly created attribute provider to bring attributes from a database or an external web service should I do the implementation inside the `get(...)` method right? Could you point any guidelines/resources on this since I have not found any so far on the web please?

**Comment by cdanger** [comment]
OK, the example in the doc was a bit obsolete, sorry for that, now it is [fixed](https://authzforce-ce-fiware.readthedocs.io/en/latest/UserAndProgrammersGuide.html#managing-attribute-providers-configuration) (TestAttributeProviderDescriptor in the xml input).

For your custom attribute provider, yes, you would do the fetching of your attribute (from db or whatever) in the [AttributeProvider#get(...)](https://javadoc.io/static/org.ow2.authzforce/authzforce-ce-core-pdp-api/15.3.0/org/ow2/authzforce/core/pdp/api/AttributeProvider.html#get-org.ow2.authzforce.core.pdp.api.AttributeFqn-org.ow2.authzforce.core.pdp.api.value.Datatype-org.ow2.authzforce.core.pdp.api.EvaluationContext-) method. This is the one called when a request is evaluated by the PDP. [More info on request evaluation on the wiki](https://github.com/authzforce/core/wiki/Attribute-Providers#request-evaluation). There is an unofficial database-oriented example provided by another user [here](https://github.com/authzforce/core/issues/27).

**Comment by Nickath** [comment]
Thanks a lot for your help, really appreciate it!
