### ISSUE TITLE
hello, I want to use this for researching XACML. Can you help me to do?

### ISSUE THREAD

**Issue by GichanLee** [authzforce/core#5]
There is some description how to start this engine but it's too simple to me.
Can you provide more more detailed description to start?
i.e.) how to write the configuration file or working_sample.xsd.
I'm a novice but I will try to do my best.
Thanks!

**Comment by GichanLee** [comment]
i.e.) how to write the configuration file.

**Comment by GichanLee** [comment]
i.e.) how to write that

**Comment by cdanger** [comment]
Hello,
I updated the README to give a basic example of working PDP configuration. If you need extra PDP features, you can look at the [XML schema](https://github.com/authzforce/core/blob/develop/src/main/resources/pdp.xsd) to understand how to enable/use them, as explained in the README.
However, if you have further questions, please send an email to [Authzforce contact mailing list](http://scr.im/azteam) for this purpose, as mentioned in the Support section of the README. This page is only for reporting issues or requesting missing features. Thanks :)
