### ISSUE TITLE
org.ow2.authzforce.core.pdp.testutil.ext.xsd MongoDBPolicyProvider ServerHost Pattern

### ISSUE THREAD

**Issue by zts3y** [authzforce/core#59]
# Software version (AuthzForce Core)

# Platform JRE

# Platform OS
All

For MongoDB policy provider, the ServerHost pattern doesn't appear to accept valid IP addresses per the pattern. What is the expectation for this flag as it wouldn't be best practice to place the database and application together on the same instance/container. All the examples use localhost, but I can't seem to find any other examples of how to connect to an external database.

**Comment by cdanger** [comment]
the serverHost expects either 'localhost' or a FQDN (fully qualidifed domain name). If you don't have a FQDN for this IP address - as you should if it is on a remote server - just make up one and add the hostname-IP mapping in the /etc/hosts file.

**Comment by cdanger** [comment]
No further comment. Closing.
