### ISSUE TITLE
Mutli requests in the use of CLI

### ISSUE THREAD

**Issue by nanoponge** [authzforce/core#65]
When I want to wirte more than one request in the request.xml and test with CLI, how should I write the request.xml?

**Comment by cdanger** [comment]
Are you referring to the [Multiple Decision Profile](http://docs.oasis-open.org/xacml/3.0/multiple/v1.0/xacml-3.0-multiple-v1.0.html)? Are the requests related to each other somehow?
Maybe give an example in a pseudo language or, even better, show the various XACML requests.xml that you'd like to merge.

**Comment by cdanger** [comment]
No reply in 6 months, closing.
