### ISSUE TITLE
The permit-unless-deny in policySet and policy produce an error

### ISSUE THREAD

**Issue by JavaUnchained** [authzforce/core#83]
# Software version (AuthzForce Core)
20.3.1
# Platform JRE
Java 13
# Platform OS
Windows

Hi. Faced with the following problem. I really hope for your help

I have a set of policies with  urn:oasis:names:tc:xacml:3.0:policy-combining-algorithm:permit-unless-deny , my policy set has a policy with the urn:oasis:names:tc:xacml:3.0:rule-combining-algorithm:permit-unless-deny . 
And I get the following kind of exception  java.util.NoSuchElementException (see error_trace.txt):
[error_trace.txt](https://github.com/authzforce/core/files/12550959/error_trace.txt)

My pdp and policy: 
[pdp.txt](https://github.com/authzforce/core/files/12550961/pdp.txt)
[BasePagePolicySet.txt](https://github.com/authzforce/core/files/12550962/BasePagePolicySet.txt)

![image](https://github.com/authzforce/core/assets/45318753/ffcb1eb1-4019-4b19-b95d-098deec10144)

My problem part of the alfa code looks like this:

```
namespace Test.Policy{
    import System.*
   
    policyset root {
        target clause Attributes.actionId == "UI" and Attributes.resourceId == "Client"
        
        apply permitUnlessDeny
        policy Manager {
            apply permitUnlessDeny
            rule subjectHasAccessCustomerManagement{
                permit
                condition axiomatics.demo.user.role == "manager"
                on permit
                {
                    advice axiomatics.demo.Test.Advise.DemoAdviceOn {
                        axiomatics.demo.Test.Advise.DemoAdvice = stringBag("VIEW","READ","WRITE")
                    } 
                }
            }
        }
    }
}
```

And I noticed that if I change it to any of the two options below, then everything will work.
First solving:

```
namespace Test.Policy{
    import System.*
  
  
    policyset root {
        target clause Attributes.actionId == "UI" and Attributes.resourceId == "Client"
        
        apply permitUnlessDeny
        policy Manager {
            apply permitUnlessDeny
            rule subjectHasAccessCustomerManagement{
                permit
                condition axiomatics.demo.user.role == "manager"
                // on permit
                // {
                //     advice axiomatics.demo.Test.Advise.DemoAdviceOn {
                //         axiomatics.demo.Test.Advise.DemoAdvice = stringBag("VIEW","READ","WRITE")
                //     } 
                // }
            }
        }
    }
}
```

Second solving

```
namespace Test.Policy{
    import System.*
  
  
    policyset root {
        target clause Attributes.actionId == "UI" and Attributes.resourceId == "Client"
        
        apply permitUnlessDeny
        policy Manager {
            apply permitUnlessDeny
            rule subjectHasAccessCustomerManagement{
                deny
                condition not(axiomatics.demo.user.role == "manager")
                on permit
                {
                    advice axiomatics.demo.Test.Advise.DemoAdviceOn {
                        axiomatics.demo.Test.Advise.DemoAdvice = stringBag("VIEW","READ","WRITE")
                    } 
                }
            }
        }
    }
}
```

And third solving is replace policy algorithm from permit-unless-deny to permit-override

Is it a bug in my xacml code or is it a bug in the pdp engine ? I apologize in advance if the questions are stupid, I'm new to xacml.

And thank you so much for your hard work and this wonderful project!

**Comment by cdanger** [comment]
Hi, I can reproduce with Java 11, this looks like a bug :-( . Will check.

**Comment by cdanger** [comment]
Fixed in the new release.

**Comment by JavaUnchained** [comment]
Thanks a lot, everything works correctly!
