### ISSUE TITLE
Timeline for migrating the javax namespace

### ISSUE THREAD

**Issue by gogolander** [authzforce/core#86]
**Is your feature request related to a problem? Please describe.**
My team is using authzforce as policy enforcer since 5 years ago. We all are painfully aware that the javax namespace has been moved to jakarta namespace. I saw that in the version 20.3.1 you guys migrated from javax.mail to jakarta.mail. But using the latest authzforce with java 17 raises a bunch of runtime exceptions related to the JAXB dependencies in the core package.
Do you guys have plans to migrate all javax.xml dependencies to jakarta? If so, could you share an approximate timeline for the release?

**Describe the solution you'd like**
We'd like to have all javax.xml dependencies moved to jakarta.

**Describe alternatives you've considered**
Currently we are packaging authz dependencies in a purpose-built jar.

**Comment by cdanger** [comment]
Yes, we had plans but we were waiting for all the JAXB tools/plugins we use in authzforce to make the move as well, especially the jaxb-maven-plugin. Good news is the [release v3.0.0](https://github.com/highsource/jaxb-tools/releases/tag/3.0.0) of that plugin last week solved it. So I think it's time for migration indeed.

Other plugin dependencies:
- jaxb-maven-plugin supports JAXB 4.0.0
- immutable-xjc-plugin supports JAXB 4.0.3
- jakarta.xml.ws-api supports JAXB 4.0.0
- jaxb2-value-constructor compatible with3.0 only? not sure about 4.0.x

This month is quite busy, but I am planning to address this by end of next month.

**Comment by gogolander** [comment]
Thanks for the update. I'm looking forward to the new release :)
